- name: User add
  hosts: Server
  become: yes

  vars:
    user: suryk
    passwordu: 'password'
  tasks:
    - name: creat users
      user:
        name: "{{ user }}"
        password: "{{ passwordu | password_hash('sha512') }}"


    - name: add sudores line
      lineinfile:
        path: /etc/sudoers
        line: "{{ user }}	ALL=(ALL)	ALL"
        insertafter: "## Allow root to run any commands anywhere"

